// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALBW_ckxN68di61ceivmuBS8_BNuVLcFY',
    appId: '1:700847464393:web:bef80be1b5d3c5053d5218',
    messagingSenderId: '700847464393',
    projectId: 'yescoach-1761b',
    authDomain: 'yescoach-1761b.firebaseapp.com',
    databaseURL: 'https://yescoach-1761b.firebaseio.com',
    storageBucket: 'yescoach-1761b.appspot.com',
    measurementId: 'G-QEJ52Y82GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrlIW11WzEW-Ej4GTmeca43iA533ebUAI',
    appId: '1:700847464393:android:21909603264efd843d5218',
    messagingSenderId: '700847464393',
    projectId: 'yescoach-1761b',
    databaseURL: 'https://yescoach-1761b.firebaseio.com',
    storageBucket: 'yescoach-1761b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVO7UxxeMU-G-ZvAWEvtapE0abWBKRgm4',
    appId: '1:700847464393:ios:5470fc1179013e6f3d5218',
    messagingSenderId: '700847464393',
    projectId: 'yescoach-1761b',
    databaseURL: 'https://yescoach-1761b.firebaseio.com',
    storageBucket: 'yescoach-1761b.appspot.com',
    androidClientId: '700847464393-37kicd8nvi4sm2fb89in49pn5hjh1gm2.apps.googleusercontent.com',
    iosClientId: '700847464393-0a0r8v01s65ce9pig083gh0ggrjmj02f.apps.googleusercontent.com',
    iosBundleId: 'com.shawoozy.yescoach',
  );
}
